package com.example.servlets;

public class HtmlTemplate {

    public static String renderPage(String contextPath, String title, String activeNav, String bodyContent, String alertMessage, String alertType) {
        StringBuilder sb = new StringBuilder();
        sb.append("<!DOCTYPE html>\n");
        sb.append("<html lang=\"es\">\n<head>\n");
        sb.append("<meta charset=\"UTF-8\">\n");
        sb.append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
        sb.append("<title>").append(title).append(" - MusicDiscography</title>\n");
        sb.append("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n");
        sb.append("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n");
        sb.append("<link href=\"https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700&display=swap\" rel=\"stylesheet\">\n");
        sb.append("<style>\n");
        sb.append(":root {\n");
        sb.append("  --bg: #0f172a;\n");
        sb.append("  --card-bg: #1e293b;\n");
        sb.append("  --card-border: #334155;\n");
        sb.append("  --text-main: #f8fafc;\n");
        sb.append("  --text-muted: #94a3b8;\n");
        sb.append("  --primary: #6366f1;\n");
        sb.append("  --primary-hover: #4f46e5;\n");
        sb.append("  --accent: #ec4899;\n");
        sb.append("  --success: #10b981;\n");
        sb.append("  --danger: #ef4444;\n");
        sb.append("  --radius: 12px;\n");
        sb.append("}\n");
        sb.append("* { box-sizing: border-box; margin: 0; padding: 0; }\n");
        sb.append("body {\n");
        sb.append("  font-family: 'Plus Jakarta Sans', system-ui, sans-serif;\n");
        sb.append("  background-color: var(--bg);\n");
        sb.append("  color: var(--text-main);\n");
        sb.append("  min-height: 100vh;\n");
        sb.append("  line-height: 1.5;\n");
        sb.append("}\n");
        sb.append("header {\n");
        sb.append("  background: rgba(30, 41, 59, 0.85);\n");
        sb.append("  backdrop-filter: blur(12px);\n");
        sb.append("  border-bottom: 1px solid var(--card-border);\n");
        sb.append("  position: sticky;\n");
        sb.append("  top: 0;\n");
        sb.append("  z-index: 100;\n");
        sb.append("}\n");
        sb.append(".nav-container {\n");
        sb.append("  max-width: 1200px;\n");
        sb.append("  margin: 0 auto;\n");
        sb.append("  padding: 0.85rem 1.5rem;\n");
        sb.append("  display: flex;\n");
        sb.append("  align-items: center;\n");
        sb.append("  justify-content: space-between;\n");
        sb.append("  flex-wrap: wrap;\n");
        sb.append("  gap: 1rem;\n");
        sb.append("}\n");
        sb.append(".brand {\n");
        sb.append("  display: flex;\n");
        sb.append("  align-items: center;\n");
        sb.append("  gap: 0.5rem;\n");
        sb.append("  font-size: 1.2rem;\n");
        sb.append("  font-weight: 700;\n");
        sb.append("  color: #fff;\n");
        sb.append("  text-decoration: none;\n");
        sb.append("}\n");
        sb.append(".brand span { color: var(--primary); }\n");
        sb.append(".nav-links {\n");
        sb.append("  display: flex;\n");
        sb.append("  align-items: center;\n");
        sb.append("  gap: 0.4rem;\n");
        sb.append("  flex-wrap: wrap;\n");
        sb.append("}\n");
        sb.append(".nav-item {\n");
        sb.append("  color: var(--text-muted);\n");
        sb.append("  text-decoration: none;\n");
        sb.append("  font-size: 0.875rem;\n");
        sb.append("  font-weight: 500;\n");
        sb.append("  padding: 0.45rem 0.8rem;\n");
        sb.append("  border-radius: 8px;\n");
        sb.append("  transition: all 0.2s;\n");
        sb.append("}\n");
        sb.append(".nav-item:hover, .nav-item.active {\n");
        sb.append("  color: #fff;\n");
        sb.append("  background: rgba(99, 102, 241, 0.15);\n");
        sb.append("}\n");
        sb.append(".nav-item.active {\n");
        sb.append("  color: #a5b4fc;\n");
        sb.append("  font-weight: 600;\n");
        sb.append("}\n");
        sb.append(".container {\n");
        sb.append("  max-width: 1200px;\n");
        sb.append("  margin: 2rem auto;\n");
        sb.append("  padding: 0 1.5rem;\n");
        sb.append("}\n");
        sb.append(".card {\n");
        sb.append("  background: var(--card-bg);\n");
        sb.append("  border: 1px solid var(--card-border);\n");
        sb.append("  border-radius: var(--radius);\n");
        sb.append("  padding: 1.75rem;\n");
        sb.append("  box-shadow: 0 10px 25px -5px rgba(0, 0, 0, 0.3);\n");
        sb.append("  margin-bottom: 2rem;\n");
        sb.append("}\n");
        sb.append(".page-header {\n");
        sb.append("  display: flex;\n");
        sb.append("  justify-content: space-between;\n");
        sb.append("  align-items: center;\n");
        sb.append("  margin-bottom: 1.5rem;\n");
        sb.append("  flex-wrap: wrap;\n");
        sb.append("  gap: 1rem;\n");
        sb.append("}\n");
        sb.append(".page-title {\n");
        sb.append("  font-size: 1.5rem;\n");
        sb.append("  font-weight: 700;\n");
        sb.append("  color: #fff;\n");
        sb.append("}\n");
        sb.append(".btn {\n");
        sb.append("  display: inline-flex;\n");
        sb.append("  align-items: center;\n");
        sb.append("  gap: 0.5rem;\n");
        sb.append("  padding: 0.6rem 1.2rem;\n");
        sb.append("  font-size: 0.9rem;\n");
        sb.append("  font-weight: 600;\n");
        sb.append("  border-radius: 8px;\n");
        sb.append("  border: none;\n");
        sb.append("  cursor: pointer;\n");
        sb.append("  text-decoration: none;\n");
        sb.append("  transition: background 0.2s, transform 0.1s;\n");
        sb.append("}\n");
        sb.append(".btn:active { transform: scale(0.98); }\n");
        sb.append(".btn-primary { background: var(--primary); color: #fff; }\n");
        sb.append(".btn-primary:hover { background: var(--primary-hover); }\n");
        sb.append(".btn-danger { background: var(--danger); color: #fff; }\n");
        sb.append(".btn-danger:hover { background: #dc2626; }\n");
        sb.append(".btn-secondary { background: #334155; color: #f8fafc; }\n");
        sb.append(".btn-secondary:hover { background: #475569; }\n");
        sb.append(".alert {\n");
        sb.append("  padding: 1rem 1.25rem;\n");
        sb.append("  border-radius: 8px;\n");
        sb.append("  margin-bottom: 1.5rem;\n");
        sb.append("  font-size: 0.95rem;\n");
        sb.append("  font-weight: 500;\n");
        sb.append("}\n");
        sb.append(".alert-success { background: rgba(16, 185, 129, 0.15); border: 1px solid #059669; color: #34d399; }\n");
        sb.append(".alert-danger { background: rgba(239, 68, 68, 0.15); border: 1px solid #b91c1c; color: #f87171; }\n");
        sb.append(".alert-info { background: rgba(99, 102, 241, 0.15); border: 1px solid #4f46e5; color: #a5b4fc; }\n");
        sb.append("table {\n");
        sb.append("  width: 100%;\n");
        sb.append("  border-collapse: collapse;\n");
        sb.append("  font-size: 0.9rem;\n");
        sb.append("  text-align: left;\n");
        sb.append("}\n");
        sb.append("th {\n");
        sb.append("  background: #111827;\n");
        sb.append("  color: #cbd5e1;\n");
        sb.append("  padding: 0.85rem 1rem;\n");
        sb.append("  font-weight: 600;\n");
        sb.append("  border-bottom: 2px solid var(--card-border);\n");
        sb.append("}\n");
        sb.append("td {\n");
        sb.append("  padding: 0.85rem 1rem;\n");
        sb.append("  border-bottom: 1px solid rgba(51, 65, 85, 0.5);\n");
        sb.append("  color: #e2e8f0;\n");
        sb.append("}\n");
        sb.append("tr:hover td { background: rgba(51, 65, 85, 0.3); }\n");
        sb.append(".badge {\n");
        sb.append("  display: inline-block;\n");
        sb.append("  padding: 0.25rem 0.6rem;\n");
        sb.append("  border-radius: 9999px;\n");
        sb.append("  font-size: 0.75rem;\n");
        sb.append("  font-weight: 600;\n");
        sb.append("  background: rgba(99, 102, 241, 0.2);\n");
        sb.append("  color: #c7d2fe;\n");
        sb.append("  margin: 0.15rem;\n");
        sb.append("}\n");
        sb.append(".badge-pink { background: rgba(236, 72, 153, 0.2); color: #fbcfe8; }\n");
        sb.append(".badge-green { background: rgba(16, 185, 129, 0.2); color: #a7f3d0; }\n");
        sb.append(".form-group {\n");
        sb.append("  margin-bottom: 1.25rem;\n");
        sb.append("}\n");
        sb.append("label {\n");
        sb.append("  display: block;\n");
        sb.append("  font-size: 0.875rem;\n");
        sb.append("  font-weight: 600;\n");
        sb.append("  margin-bottom: 0.4rem;\n");
        sb.append("  color: #cbd5e1;\n");
        sb.append("}\n");
        sb.append("input[type=\"text\"], input[type=\"number\"], select {\n");
        sb.append("  width: 100%;\n");
        sb.append("  padding: 0.65rem 1rem;\n");
        sb.append("  background: #0f172a;\n");
        sb.append("  border: 1px solid var(--card-border);\n");
        sb.append("  border-radius: 8px;\n");
        sb.append("  color: #fff;\n");
        sb.append("  font-size: 0.95rem;\n");
        sb.append("  outline: none;\n");
        sb.append("  transition: border-color 0.2s;\n");
        sb.append("}\n");
        sb.append("input[type=\"text\"]:focus, input[type=\"number\"]:focus, select:focus {\n");
        sb.append("  border-color: var(--primary);\n");
        sb.append("}\n");
        sb.append(".checkbox-list {\n");
        sb.append("  max-height: 200px;\n");
        sb.append("  overflow-y: auto;\n");
        sb.append("  background: #0f172a;\n");
        sb.append("  border: 1px solid var(--card-border);\n");
        sb.append("  border-radius: 8px;\n");
        sb.append("  padding: 0.75rem;\n");
        sb.append("}\n");
        sb.append(".checkbox-item {\n");
        sb.append("  display: flex;\n");
        sb.append("  align-items: center;\n");
        sb.append("  gap: 0.5rem;\n");
        sb.append("  padding: 0.35rem 0;\n");
        sb.append("  color: #e2e8f0;\n");
        sb.append("  font-size: 0.9rem;\n");
        sb.append("}\n");
        sb.append(".checkbox-item input { accent-color: var(--primary); }\n");
        sb.append("</style>\n</head>\n<body>\n");

        // Header & Navigation
        sb.append("<header>\n<div class=\"nav-container\">\n");
        sb.append("  <a href=\"").append(contextPath).append("/\" class=\"brand\">🎵 Music<span>Discography</span></a>\n");
        sb.append("  <nav class=\"nav-links\">\n");
        sb.append("    <a href=\"").append(contextPath).append("/artists\" class=\"nav-item ").append("artists".equals(activeNav) ? "active" : "").append("\">👥 Artistas</a>\n");
        sb.append("    <a href=\"").append(contextPath).append("/artists/create\" class=\"nav-item ").append("artist-create".equals(activeNav) ? "active" : "").append("\">➕ Crear Artista</a>\n");
        sb.append("    <a href=\"").append(contextPath).append("/artists/search\" class=\"nav-item ").append("artist-search".equals(activeNav) ? "active" : "").append("\">🔍 Buscar Artista</a>\n");
        sb.append("    <a href=\"").append(contextPath).append("/artists/delete\" class=\"nav-item ").append("artist-delete".equals(activeNav) ? "active" : "").append("\">🗑️ Eliminar Artista</a>\n");
        sb.append("    <a href=\"").append(contextPath).append("/tracks\" class=\"nav-item ").append("tracks".equals(activeNav) ? "active" : "").append("\">🎶 Canciones</a>\n");
        sb.append("    <a href=\"").append(contextPath).append("/tracks/create\" class=\"nav-item ").append("track-create".equals(activeNav) ? "active" : "").append("\">➕ Crear Canción</a>\n");
        sb.append("    <a href=\"").append(contextPath).append("/tracks/delete\" class=\"nav-item ").append("track-delete".equals(activeNav) ? "active" : "").append("\">🗑️ Eliminar Canción</a>\n");
        sb.append("  </nav>\n</div>\n</header>\n");

        // Main Container
        sb.append("<main class=\"container\">\n");

        if (alertMessage != null && !alertMessage.trim().isEmpty()) {
            String typeClass = (alertType != null) ? "alert-" + alertType : "alert-info";
            sb.append("<div class=\"alert ").append(typeClass).append("\">").append(alertMessage).append("</div>\n");
        }

        sb.append(bodyContent);
        sb.append("</main>\n</body>\n</html>");

        return sb.toString();
    }
}
